name: Check for new apps

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  status_check:
    if: github.repository == 'nikhilbadyal/docker-py-revanced'
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@main

      - name: setup python
        uses: actions/setup-python@main
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Status Check
        run: |
          output=$(python -m scripts.status_check)
          echo "changelog=$output" >>$GITHUB_OUTPUT
        id: status
      - name: Update Check
        run: echo "${{ steps.status.outputs.changelog }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: revanced-update/status-check
          title: Revanced apps
          commit-message: revanced-app
          body: ${{ steps.status.outputs.changelog }}
