name: Telegram Upload

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      TELEGRAM_API_ID:
        required: true
      TELEGRAM_API_HASH:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: true
      TELEGRAM_CHAT_ID:
        required: true
      STICKER_ID:
        required: true

jobs:
  tg-upload:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Telegram
        if: ${{ env.HAVE_TELEGRAM_API_ID == 'true' }}
        uses: nikhilbadyal/ghaction-telegram-uploader@main
        with:
          API_ID: ${{ secrets.TELEGRAM_API_ID }}
          API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          STICKER_ID: ${{ secrets.STICKER_ID }}
env:
  HAVE_TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID != '' }}
