name: VirusTotal Scan

on:
  workflow_run:
    workflows: [ "Build Revanced APK" ]
    types:
      - completed
  workflow_dispatch: # to trigger manually

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        uses: nikhilbadyal/ghaction-virustotal@master
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release_body: true
          github_token: ${{ secrets.GH_TOKEN }}
          request_rate: 4
          files: |
            .apk$
